This Jupyter Notebook continues my data cleaning and processing with more documentation. Note that so far I have narrowed done my datasets from 74 to 18 and I've eliminated unhelpful columns like phone numbers and dates.

The next step is to join data. I start by loading the data as Pandas Data Frames, then I view all the headers to decide on the best way to join the data and see any remaining unnecessary columns that I should remove first.

In [57]:
# Imports
import pandas as pd
import numpy as np

In [85]:
# Load files
ascqr = pd.read_csv('./reduced_data/ASCQR_OAS_CAHPS_BY_ASC.csv')
cjr = pd.read_csv('./reduced_data/CJR_Quality_Reporting_January_2025_Production_File.csv')
complicationsdeaths = pd.read_csv('./reduced_data/Complications_and_Deaths-Hospital.csv')
fy_hac = pd.read_csv('./reduced_data/FY_2025_HAC_Reduction_Program_Hospital.csv')
fy_readmissions = pd.read_csv('./reduced_data/FY_2025_Hospital_Readmissions_Reduction_Program_Hospital.csv')
hcahps = pd.read_csv('./reduced_data/HCAHPS-Hospital.csv')
hai = pd.read_csv('./reduced_data/Healthcare_Associated_Infections-Hospital.csv')
hgi = pd.read_csv('./reduced_data/Hospital_General_Information.csv')
hvbp_clinical = pd.read_csv('./reduced_data/hvbp_clinical_outcomes.csv')
hvbp_efficiency = pd.read_csv('./reduced_data/hvbp_efficiency_and_cost_reduction.csv')
hvbp_engagement = pd.read_csv('./reduced_data/hvbp_person_and_community_engagement.csv')
hvbp_safety = pd.read_csv('./reduced_data/hvbp_safety.csv')
hvbp_tps = pd.read_csv('./reduced_data/hvbp_tps.csv')
medicare_claim = pd.read_csv('./reduced_data/Medicare_Hospital_Spending_by_Claim.csv')
medicare_per_patient = pd.read_csv('./reduced_data/Medicare_Hospital_Spending_Per_Patient-Hospital.csv')
outpatient_imaging = pd.read_csv('./reduced_data/Outpatient_Imaging_Efficiency-Hospital.csv')
payment_value = pd.read_csv('./reduced_data/Payment_and_Value_of_Care-Hospital.csv')
unplanned_visits = pd.read_csv('./reduced_data/Unplanned_Hospital_Visits-Hospital.csv', low_memory=False)

In [14]:
ascqr.head()

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score
0,MEDPLEX OUTPATIENT SURGERY CENTER LTD,BIRMINGHAM,AL,98.0,97.0,96.0,96.0
1,GULF COAST SURGICAL PARTNERS LLC,MOBILE,AL,98.0,95.0,95.0,95.0
2,SHELBY BAPTIST AMBULATORY SURGERY CENTER LLC,ALABASTER,AL,NaN,NaN,NaN,NaN
3,ALABAMA DIGESTIVE HEALTH ENDOSCOPY CENTER LLC,BIRMINGHAM,AL,98.0,95.0,95.0,93.0
4,JACKSON SURGERY CENTER LLC,MONTGOMERY,AL,98.0,95.0,95.0,95.0

In [17]:
cjr.head()

,Facility Name,MSA Title,HCAHPS HLMR Percentile
0,BAPTIST MEDICAL CENTER SOUTH,"Montgomery, AL",48%
1,CHI ST. VINCENT HOSPITAL HOT SPRINGS,"Hot Springs, AR",45%
2,NATIONAL PARK MEDICAL CENTER,"Hot Springs, AR",9%
3,ANTELOPE VALLEY HOSPITAL,"Los Angeles-Long Beach-Anaheim, CA",5%
4,PROVIDENCE ST JOSEPH HOSPITAL,"Los Angeles-Long Beach-Anaheim, CA",66%

In [18]:
complicationsdeaths.head()

,Facility Name,City/Town,State,County/Parish,Measure ID,Measure Name,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,32,3,1.6,5.5
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,291,10.8,8.4,13.6
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,157,3.8,2.1,6.8
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,122,7.9,5.2,11.9
4,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,610,10.5,8.6,12.9

In [86]:
fy_hac.head()

                     Facility Name State  Total HAC Score
0  SOUTHEAST HEALTH MEDICAL CENTER    AL          -0.0550
1         MARSHALL MEDICAL CENTERS    AL           0.6475
2     NORTH ALABAMA MEDICAL CENTER    AL          -0.5397
3         MIZELL MEMORIAL HOSPITAL    AL          -0.3427
4      CRENSHAW COMMUNITY HOSPITAL    AL              NaN

In [82]:
fy_readmissions.head()

,Facility Name,State,Measure Name,Excess Readmission Ratio
0,SOUTHEAST HEALTH MEDICAL CENTER,AL,READM-30-AMI-HRRP,0.9483
1,SOUTHEAST HEALTH MEDICAL CENTER,AL,READM-30-CABG-HRRP,0.9509
2,SOUTHEAST HEALTH MEDICAL CENTER,AL,READM-30-HF-HRRP,1.0597
3,SOUTHEAST HEALTH MEDICAL CENTER,AL,READM-30-HIP-KNEE-HRRP,0.9654
4,SOUTHEAST HEALTH MEDICAL CENTER,AL,READM-30-PN-HRRP,0.9715

In [23]:
hcahps.head()

,Facility Name,City/Town,State,County/Parish,HCAHPS Measure ID,HCAHPS Question,HCAHPS Answer Description,Patient Survey Star Rating,HCAHPS Answer Percent
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,H_COMP_1_A_P,"Patients who reported that their nurses ""Alway...","Nurses ""always"" communicated well",Not Applicable,71
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,H_COMP_1_SN_P,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" communicated well",Not Applicable,6
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,H_COMP_1_U_P,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" communicated well",Not Applicable,23
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,H_COMP_1_LINEAR_SCORE,Nurse communication - linear mean score,Nurse communication - linear mean score,Not Applicable,Not Applicable
4,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,H_COMP_1_STAR_RATING,Nurse communication - star rating,Nurse communication - star rating,2,Not Applicable

In [24]:
hai.head()

,Facility Name,City/Town,State,County/Parish,Measure ID,Measure Name,Compared to National,Score
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,HAI_1_CILOWER,Central Line Associated Bloodstream Infection ...,No Different than National Benchmark,0.194
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,HAI_1_CIUPPER,Central Line Associated Bloodstream Infection ...,No Different than National Benchmark,1.171
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,HAI_1_DOPC,Central Line Associated Bloodstream Infection:...,No Different than National Benchmark,8926
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,HAI_1_ELIGCASES,Central Line Associated Bloodstream Infection ...,No Different than National Benchmark,9.461
4,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,HAI_1_NUMERATOR,Central Line Associated Bloodstream Infection ...,No Different than National Benchmark,5

In [25]:
hgi.head()

,Facility Name,City/Town,State,County/Parish,Hospital overall rating
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,3
1,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,2
2,NORTH ALABAMA MEDICAL CENTER,FLORENCE,AL,LAUDERDALE,1
3,MIZELL MEMORIAL HOSPITAL,OPP,AL,COVINGTON,1
4,CRENSHAW COMMUNITY HOSPITAL,LUVERNE,AL,CRENSHAW,Not Available

In [26]:
hvbp_clinical.head()

,Facility Name,City/Town,State,County/Parish,MORT-30-AMI Measure Score,MORT-30-HF Measure Score,MORT-30-PN Measure Score,MORT-30-COPD Measure Score,MORT-30-CABG Measure Score,COMP-HIP-KNEE Measure Score
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,10 out of 10,5 out of 10,0 out of 10,3 out of 10,2 out of 10,4 out of 10
1,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,0 out of 10,4 out of 10,0 out of 10,3 out of 10,Not Available,4 out of 10
2,NORTH ALABAMA MEDICAL CENTER,FLORENCE,AL,LAUDERDALE,0 out of 10,0 out of 10,0 out of 10,1 out of 10,0 out of 10,0 out of 10
3,MIZELL MEMORIAL HOSPITAL,OPP,AL,COVINGTON,Not Available,0 out of 10,0 out of 10,0 out of 10,Not Available,0 out of 10
4,ST. VINCENT'S EAST,BIRMINGHAM,AL,JEFFERSON,4 out of 10,0 out of 10,0 out of 10,0 out of 10,9 out of 10,0 out of 10

In [27]:
hvbp_efficiency.head()

,Facility Name,City/Town,State,County/Parish,MSPB-1 Measure Score
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,0 out of 10
1,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,0 out of 10
2,NORTH ALABAMA MEDICAL CENTER,FLORENCE,AL,LAUDERDALE,0 out of 10
3,MIZELL MEMORIAL HOSPITAL,OPP,AL,COVINGTON,0 out of 10
4,ST. VINCENT'S EAST,BIRMINGHAM,AL,JEFFERSON,0 out of 10

In [28]:
hvbp_engagement.head()

,Facility Name,City/Town,State,County/Parish,Communication With Nurses Dimension Score,Communication With Doctors Dimension Score,Responsiveness Of Hospital Staff Dimension Score,Care Transition Dimension Score,Communication About Medicines Dimension Score,Cleanliness And Quietness Of Hospital Environment Dimension Score,Discharge Information Dimension Score,Overall Rating Of Hospital Dimension Score,Hcahps Base Score,Hcahps Consistency Score
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,0,0,0,1,0,0,0,0,1,13
1,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,0,2,0,1,0,1,0,0,4,10
2,NORTH ALABAMA MEDICAL CENTER,FLORENCE,AL,LAUDERDALE,0,0,0,0,0,0,0,0,0,8
3,MIZELL MEMORIAL HOSPITAL,OPP,AL,COVINGTON,1,5,2,0,0,0,10,2,20,18
4,ST. VINCENT'S EAST,BIRMINGHAM,AL,JEFFERSON,0,0,0,0,0,0,0,0,0,13

In [29]:
hvbp_safety.head()

,Facility Name,City/Town,State,County/Parish,Combined SSI Measure Score,HAI-3 Measure Score,HAI-4 Measure Score,HAI-5 Measure Score,HAI-6 Measure Score
0,ACADIA GENERAL HOSPITAL,CROWLEY,LA,ACADIA,0 out of 10,0 out of 10,Not Available,Not Available,3 out of 10
1,RIVERSIDE SHORE MEMORIAL HOSPITAL,ONANCOCK,VA,ACCOMACK,Not Available,Not Available,Not Available,Not Available,10 out of 10
2,SAINT ALPHONSUS REGIONAL MEDICAL CENTER,BOISE,ID,ADA,3 out of 10,3 out of 10,0 out of 10,6 out of 10,1 out of 10
3,ST LUKE'S REGIONAL MEDICAL CENTER,BOISE,ID,ADA,0 out of 10,0 out of 10,0 out of 10,5 out of 10,3 out of 10
4,NORTHEAST REGIONAL MEDICAL CENTER,KIRKSVILLE,MO,ADAIR,Not Available,Not Available,Not Available,Not Available,3 out of 10

In [30]:
hvbp_tps.head()

,Facility Name,City/Town,State,County/Parish,Total Performance Score
0,ACADIA GENERAL HOSPITAL,CROWLEY,LA,ACADIA,20.125000
1,RIVERSIDE SHORE MEMORIAL HOSPITAL,ONANCOCK,VA,ACCOMACK,35.166667
2,SAINT ALPHONSUS REGIONAL MEDICAL CENTER,BOISE,ID,ADA,15.500000
3,ST LUKE'S REGIONAL MEDICAL CENTER,BOISE,ID,ADA,20.750000
4,NORTHEAST REGIONAL MEDICAL CENTER,KIRKSVILLE,MO,ADAIR,35.250000

In [31]:
medicare_claim.head()

,Facility Name,State,Claim Type,Avg Spndg Per EP Hospital,Avg Spndg Per EP State,Avg Spndg Per EP National,Percent of Spndg Hospital,Percent of Spndg State,Percent of Spndg National
0,SOUTHEAST HEALTH MEDICAL CENTER,AL,Home Health Agency,28,23,19,0.10%,0.09%,0.07%
1,SOUTHEAST HEALTH MEDICAL CENTER,AL,Hospice,1,2,1,0.00%,0.01%,0.00%
2,SOUTHEAST HEALTH MEDICAL CENTER,AL,Inpatient,37,39,45,0.13%,0.15%,0.17%
3,SOUTHEAST HEALTH MEDICAL CENTER,AL,Outpatient,148,126,190,0.52%,0.49%,0.71%
4,SOUTHEAST HEALTH MEDICAL CENTER,AL,Skilled Nursing Facility,15,11,16,0.05%,0.04%,0.06%

In [32]:
medicare_per_patient.head()

                     Facility Name City/Town State County/Parish Score
0  SOUTHEAST HEALTH MEDICAL CENTER    DOTHAN    AL       HOUSTON  1.03
1         MARSHALL MEDICAL CENTERS      BOAZ    AL      MARSHALL     1
2     NORTH ALABAMA MEDICAL CENTER  FLORENCE    AL    LAUDERDALE  1.02
3         MIZELL MEMORIAL HOSPITAL       OPP    AL     COVINGTON  1.02
4      CRENSHAW COMMUNITY HOSPITAL   LUVERNE    AL      CRENSHAW  1.07

In [33]:
outpatient_imaging.head()

,Facility Name,City/Town,State,County/Parish,Measure ID,Measure Name,Score
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP-10,Abdomen CT Use of Contrast Material,5.4
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP-13,Outpatients who got cardiac imaging stress tes...,2.1
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP-39,Breast Cancer Screening Recall Rates,5.3
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP-8,MRI Lumbar Spine for Low Back Pain,33.3
4,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,OP-10,Abdomen CT Use of Contrast Material,13.4

In [34]:
payment_value.head()

,Facility Name,City/Town,State,County/Parish,Payment Measure ID,Payment Measure Name,Payment Category,Denominator,Payment,Lower Estimate,Higher Estimate,Value of Care Display ID,Value of Care Display Name,Value of Care Category
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,PAYM_30_AMI,Payment for heart attack patients,No Different Than the National Average Payment,290,"$28,502","$26,229","$30,939",MORT_PAYM_30_AMI,Value of Care Heart Attack measure,Average Mortality and Average Payment
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,PAYM_30_HF,Payment for heart failure patients,No Different Than the National Average Payment,590,"$20,602","$19,572","$21,713",MORT_PAYM_30_HF,Value of Care Heart Failure measur,Average Mortality and Average Payment
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,PAYM_30_PN,Payment for pneumonia patients,Greater Than the National Average Payment,468,"$22,404","$21,247","$23,627",MORT_PAYM_30_PN,Value of Care Pneumonia measure,Average Mortality and Higher Payment
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,PAYM_90_HIP_KNEE,Payment for hip/knee replacement patients,No Different Than the National Average Payment,32,"$22,819","$20,082","$26,007",COMP_PAYM_90_HIP_KNEE,Value of Care hip/knee replacement,Average Complications and Average Payment
4,MARSHALL MEDICAL CENTERS,BOAZ,AL,MARSHALL,PAYM_30_AMI,Payment for heart attack patients,No Different Than the National Average Payment,26,"$26,561","$22,721","$30,858",MORT_PAYM_30_AMI,Value of Care Heart Attack measure,Average Mortality and Average Payment

In [35]:
unplanned_visits.head()

,Facility Name,City/Town,State,County/Parish,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Number of Patients,Number of Patients Returned,Footnote
0,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,EDAC_30_AMI,Average Days per 100 Discharges,296,-13.8,-27.5,2.4,283,71,NaN
1,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,EDAC_30_HF,Average Days per 100 Discharges,679,10.6,-6.9,29.3,569,191,NaN
2,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,EDAC_30_PN,Average Days per 100 Discharges,490,14.3,-4.3,34.5,456,114,NaN
3,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP_32,No Different Than the National Rate,218,12.8,9.4,17.4,Not Applicable,Not Applicable,NaN
4,SOUTHEAST HEALTH MEDICAL CENTER,DOTHAN,AL,HOUSTON,OP_35_ADM,No Different Than the National Rate,261,8.5,6.3,11.5,Not Applicable,Not Applicable,NaN

Then we can begin joining one by one

In [41]:
ascqr_cjr=pd.merge(ascqr,cjr,how='outer',on='Facility Name')
ascqr_cjr.head()
ascqr_cjr.to_csv('ascqr_cjr.csv', index=False)
# This join had zero overlap...

In [ ]:
# Fix Complications and Deaths format to be one listing per facility
complicationsdeaths['Score'] = complicationsdeaths['Score'].replace('Not Available', np.nan)
fixed_compls = complicationsdeaths.pivot_table(
    index=['Facility Name', 'City/Town', 'State', 'County/Parish'],
    columns='Measure Name',
    values='Score',
    aggfunc='first'  # use first score if duplicates exist
).reset_index()
fixed_compls.columns.name = None

In [77]:
# Remove rows where most of the data is missing
measure_cols = fixed_compls.columns.difference(['Facility Name', 'City/Town', 'State', 'County/Parish'])
fixed_compls['missing_count'] = fixed_compls[measure_cols].isna().sum(axis=1)
fixed_compls = fixed_compls[fixed_compls['missing_count'] < 15].drop(columns='missing_count')

# Save to csv
fixed_compls.to_csv('fixed_compls.csv',index=False)
fixed_compls.head()

,Facility Name,City/Town,State,County/Parish,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,Death rate among surgical inpatients with serious treatable complications,Death rate for CABG surgery patients,Death rate for COPD patients,Death rate for heart attack patients,...,Iatrogenic pneumothorax rate,In-hospital fall-associated fracture rate,Perioperative pulmonary embolism or deep vein thrombosis rate,Postoperative acute kidney injury requiring dialysis rate,Postoperative hemorrhage or hematoma rate,Postoperative respiratory failure rate,Postoperative sepsis rate,Postoperative wound dehiscence rate,Pressure ulcer rate,Rate of complications for hip/knee replacement patients
1,ABBEVILLE GENERAL HOSPITAL,ABBEVILLE,LA,VERMILION,0.85,0.91,NaN,NaN,NaN,NaN,...,0.24,0.28,3.61,1.64,2.39,9.8,5.21,1.85,0.49,NaN
2,ABBOTT NORTHWESTERN HOSPITAL,MINNEAPOLIS,MN,HENNEPIN,1.17,0.93,171.56,2.5,8.8,10.1,...,0.25,0.25,3.04,2.55,1.47,10.93,7.18,1.45,0.17,2.4
4,ABRAZO ARROWHEAD HOSPITAL,GLENDALE,AZ,MARICOPA,1.59,1.12,151.96,4,10,13.2,...,0.33,0.27,3.67,1.62,3.3,14.71,5.16,2.07,0.64,3.3
5,ABRAZO CENTRAL CAMPUS,PHOENIX,AZ,MARICOPA,0.82,0.93,180.49,NaN,8.6,NaN,...,0.23,0.28,4.66,NaN,2.63,NaN,NaN,1.8,0.33,NaN
6,ABRAZO SCOTTSDALE CAMPUS,PHOENIX,AZ,MARICOPA,0.83,0.99,NaN,NaN,10.4,13,...,0.29,0.27,3.46,1.69,2.6,9.6,5.46,1.83,0.74,NaN

In [80]:
join2=pd.merge(ascqr,fixed_compls,how='outer',on=['Facility Name', 'City/Town', 'State'])
join2.to_csv('join2.csv',index=False)
join2.head()

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score,County/Parish,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,...,Iatrogenic pneumothorax rate,In-hospital fall-associated fracture rate,Perioperative pulmonary embolism or deep vein thrombosis rate,Postoperative acute kidney injury requiring dialysis rate,Postoperative hemorrhage or hematoma rate,Postoperative respiratory failure rate,Postoperative sepsis rate,Postoperative wound dehiscence rate,Pressure ulcer rate,Rate of complications for hip/knee replacement patients
0,ABBEVILLE GENERAL HOSPITAL,ABBEVILLE,LA,NaN,NaN,NaN,NaN,VERMILION,0.85,0.91,...,0.24,0.28,3.61,1.64,2.39,9.8,5.21,1.85,0.49,NaN
1,ABBOTT NORTHWESTERN HOSPITAL,MINNEAPOLIS,MN,NaN,NaN,NaN,NaN,HENNEPIN,1.17,0.93,...,0.25,0.25,3.04,2.55,1.47,10.93,7.18,1.45,0.17,2.4
2,ABRAZO ARROWHEAD HOSPITAL,GLENDALE,AZ,NaN,NaN,NaN,NaN,MARICOPA,1.59,1.12,...,0.33,0.27,3.67,1.62,3.3,14.71,5.16,2.07,0.64,3.3
3,ABRAZO CENTRAL CAMPUS,PHOENIX,AZ,NaN,NaN,NaN,NaN,MARICOPA,0.82,0.93,...,0.23,0.28,4.66,NaN,2.63,NaN,NaN,1.8,0.33,NaN
4,ABRAZO SCOTTSDALE CAMPUS,PHOENIX,AZ,NaN,NaN,NaN,NaN,MARICOPA,0.83,0.99,...,0.29,0.27,3.46,1.69,2.6,9.6,5.46,1.83,0.74,NaN

In [84]:
# Repeat for fy_readmissions
fixed_fy_readmis = fy_readmissions.pivot_table(
    index=['Facility Name', 'State'],
    columns='Measure Name',
    values='Excess Readmission Ratio',
    aggfunc='first'  # use first score if duplicates exist
).reset_index()
fixed_compls.columns.name = None
fixed_fy_readmis.head()

Measure Name,Facility Name,State,READM-30-AMI-HRRP,READM-30-CABG-HRRP,READM-30-COPD-HRRP,READM-30-HF-HRRP,READM-30-HIP-KNEE-HRRP,READM-30-PN-HRRP
0,ABBEVILLE GENERAL HOSPITAL,LA,NaN,NaN,NaN,0.9793,NaN,0.9460
1,ABBOTT NORTHWESTERN HOSPITAL,MN,0.9163,0.9322,0.9530,0.9482,0.8866,1.0253
2,ABINGTON MEMORIAL HOSPITAL,PA,0.9888,1.0194,0.9698,1.0533,0.9342,1.1645
3,ABRAZO ARROWHEAD HOSPITAL,AZ,1.1148,1.0020,1.0329,1.0169,1.0208,1.0050
4,ABRAZO CENTRAL CAMPUS,AZ,NaN,NaN,1.0001,0.9791,NaN,0.9957

In [89]:
fy=pd.merge(fy_hac,fixed_fy_readmis,how='outer',on=['Facility Name', 'State'])
fy.head()
fy.to_csv('fy',index=False)

In [93]:
join3=pd.merge(join2,fy,how='outer',on=['Facility Name','State'])
join3.to_csv('join3.csv',index=False)
join3.head()

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score,County/Parish,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,...,Postoperative wound dehiscence rate,Pressure ulcer rate,Rate of complications for hip/knee replacement patients,Total HAC Score,READM-30-AMI-HRRP,READM-30-CABG-HRRP,READM-30-COPD-HRRP,READM-30-HF-HRRP,READM-30-HIP-KNEE-HRRP,READM-30-PN-HRRP
0,ABBEVILLE GENERAL HOSPITAL,ABBEVILLE,LA,NaN,NaN,NaN,NaN,VERMILION,0.85,0.91,...,1.85,0.49,NaN,1.2678,NaN,NaN,NaN,0.9793,NaN,0.9460
1,ABBOTT NORTHWESTERN HOSPITAL,MINNEAPOLIS,MN,NaN,NaN,NaN,NaN,HENNEPIN,1.17,0.93,...,1.45,0.17,2.4,0.1330,0.9163,0.9322,0.9530,0.9482,0.8866,1.0253
2,ABINGTON MEMORIAL HOSPITAL,NaN,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.1027,0.9888,1.0194,0.9698,1.0533,0.9342,1.1645
3,ABRAZO ARROWHEAD HOSPITAL,GLENDALE,AZ,NaN,NaN,NaN,NaN,MARICOPA,1.59,1.12,...,2.07,0.64,3.3,-0.6870,1.1148,1.0020,1.0329,1.0169,1.0208,1.0050
4,ABRAZO CENTRAL CAMPUS,PHOENIX,AZ,NaN,NaN,NaN,NaN,MARICOPA,0.82,0.93,...,1.8,0.33,NaN,-0.1962,NaN,NaN,1.0001,0.9791,NaN,0.9957

In [99]:
# Once again, we must repeat our data formating fixes
# Starting by formatting null values
hcahps['Patient Survey Star Rating'] = hcahps['Patient Survey Star Rating'].replace('Not Applicable', np.nan)
hcahps['HCAHPS Answer Percent']  = hcahps['HCAHPS Answer Percent'].replace('Not Applicable', np.nan)
# Combine value columns to one
hcahps['Value'] = hcahps['Patient Survey Star Rating'].combine_first(hcahps['HCAHPS Answer Percent'])
hcahps['Value'] = pd.to_numeric(hcahps['Value'], errors='coerce')
# Make pivot table
hcahps_pivot = hcahps.pivot_table(
    index=['Facility Name', 'City/Town', 'State', 'County/Parish'],
    columns='HCAHPS Answer Description',
    values='Value',
    aggfunc='first'    # if a facility/measure pair ever appears twice, just take the first
).reset_index()
hcahps_pivot.columns.name = None
hcahps_pivot.to_csv('hcahps_pivot.csv',index=False)
hcahps_pivot.head()
# 87 columns is too many I'll pull it into excel to examine and eliminate some

,Facility Name,City/Town,State,County/Parish,"""Always"" quiet at night","""NO"", patients would not recommend the hospital (they probably would not or definitely would not recommend it)","""Sometimes"" or ""never"" quiet at night","""Usually"" quiet at night","""YES"", patients would definitely recommend the hospital","""YES"", patients would probably recommend the hospital",...,"Staff ""sometimes"" or ""never"" explained new medications","Staff ""sometimes"" or ""never"" explained possible side effects","Staff ""usually"" explained","Staff ""usually"" explained new medications","Staff ""usually"" explained possible side effects",Staff responsiveness - star rating,Summary star rating,"Yes, staff ""did"" give patients information about help after discharge","Yes, staff ""did"" give patients information about possible symptoms","Yes, staff ""did"" give patients this information"
0,60th Medical Group (Travis AFB),Travis AFB,CA,SOLANO,62.0,1.0,6.0,32.0,81.0,18.0,...,8.0,17.0,18.0,14.0,22.0,5.0,5.0,87.0,94.0,90.0
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,ANCHORAGE,58.0,7.0,8.0,34.0,74.0,19.0,...,6.0,24.0,17.0,15.0,20.0,4.0,4.0,90.0,94.0,92.0
2,81st Medical Group (Keesler AFB),Biloxi,MS,HARRISON,80.0,2.0,2.0,18.0,90.0,8.0,...,3.0,16.0,15.0,11.0,19.0,5.0,5.0,89.0,94.0,92.0
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,GREENE,75.0,2.0,4.0,21.0,85.0,13.0,...,4.0,14.0,10.0,5.0,14.0,5.0,5.0,88.0,94.0,92.0
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,OKALOOSA,77.0,2.0,1.0,22.0,79.0,19.0,...,6.0,18.0,14.0,9.0,18.0,5.0,5.0,89.0,95.0,92.0

In [103]:
# Pretty sure the only value column we need is summary star rating as it's a combination of all of them
hcahps_fixed=hcahps_pivot[['Facility Name','City/Town','State','Summary star rating']]
hcahps_fixed.to_csv('hcahps_fixed.csv', index=False)
hcahps_fixed.head()

,Facility Name,City/Town,State,Summary star rating
0,60th Medical Group (Travis AFB),Travis AFB,CA,5.0
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,4.0
2,81st Medical Group (Keesler AFB),Biloxi,MS,5.0
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,5.0
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,5.0

In [ ]:
join4=pd.merge(join3,hcahps_fixed,how='outer',on=['Facility Name', 'City/Town','State'])
join4.to_csv('join4.csv',index=False)
join4.head()
# Starting to get a lot of null values to remove later...

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score,County/Parish,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,...,Pressure ulcer rate,Rate of complications for hip/knee replacement patients,Total HAC Score,READM-30-AMI-HRRP,READM-30-CABG-HRRP,READM-30-COPD-HRRP,READM-30-HF-HRRP,READM-30-HIP-KNEE-HRRP,READM-30-PN-HRRP,Summary star rating
0,60th Medical Group (Travis AFB),Travis AFB,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
2,81st Medical Group (Keesler AFB),Biloxi,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [109]:
# Repeat for hai
hai_pivot = hai.pivot_table(
    index=['Facility Name', 'City/Town', 'State'],
    columns='Measure Name',
    values='Score',
    aggfunc='first'    # if a facility/measure pair ever appears twice, just take the first
).reset_index()
hai_pivot.columns.name = None
hai_pivot.to_csv('hai_pivot.csv',index=False)
hai_pivot.head()

,Facility Name,City/Town,State,Catheter Associated Urinary Tract Infections (ICU + select Wards),Catheter Associated Urinary Tract Infections (ICU + select Wards): Lower Confidence Limit,Catheter Associated Urinary Tract Infections (ICU + select Wards): Number of Urinary Catheter Days,Catheter Associated Urinary Tract Infections (ICU + select Wards): Observed Cases,Catheter Associated Urinary Tract Infections (ICU + select Wards): Predicted Cases,Catheter Associated Urinary Tract Infections (ICU + select Wards): Upper Confidence Limit,Central Line Associated Bloodstream Infection (ICU + select Wards),...,SSI - Abdominal Hysterectomy: Number of Procedures,SSI - Abdominal Hysterectomy: Observed Cases,SSI - Abdominal Hysterectomy: Predicted Cases,SSI - Abdominal Hysterectomy: Upper Confidence Limit,SSI - Colon Surgery,SSI - Colon Surgery: Lower Confidence Limit,SSI - Colon Surgery: Number of Procedures,SSI - Colon Surgery: Observed Cases,SSI - Colon Surgery: Predicted Cases,SSI - Colon Surgery: Upper Confidence Limit
0,60th Medical Group (Travis AFB),Travis AFB,CA,Not Available,Not Available,1260,1,0.733,Not Available,Not Available,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,Not Available,Not Available,619,0,0.32,Not Available,Not Available,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
2,81st Medical Group (Keesler AFB),Biloxi,MS,Not Available,Not Available,674,0,0.383,Not Available,Not Available,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,Not Available,Not Available,366,0,0.214,Not Available,Not Available,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,Not Available,Not Available,362,0,0.21,Not Available,Not Available,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available

In [111]:
# Consolidated Data
hai_pivot=pd.read_csv('hai_pivot.csv')
hai_pivot.head()

,Facility Name,City/Town,State,Catheter Associated Infections Observed/Predicted,Central Line Blood Infections Observed/Predicted,C.Diff Observed/Predicted,MRSA Observed/Predicted,Abdominal SSI Observed/Predicted,Colon SSI
0,60th Medical Group (Travis AFB),Travis AFB,CA,1.36425648,2.34741784,2.509760178,#VALUE!,#VALUE!,#VALUE!
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,0.1,0,0,#VALUE!,#VALUE!,#VALUE!
2,81st Medical Group (Keesler AFB),Biloxi,MS,0.1,0,0,#VALUE!,#VALUE!,#VALUE!
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,0.1,0,2.132196162,#VALUE!,#VALUE!,#VALUE!
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,0.1,0,0,#VALUE!,#VALUE!,#VALUE!

In [112]:
join5=pd.merge(join4,hai_pivot,how='outer',on=['Facility Name','City/Town','State'])
join5.to_csv('join5.csv',index=False)
join5.head()

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score,County/Parish,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,...,READM-30-HF-HRRP,READM-30-HIP-KNEE-HRRP,READM-30-PN-HRRP,Summary star rating,Catheter Associated Infections Observed/Predicted,Central Line Blood Infections Observed/Predicted,C.Diff Observed/Predicted,MRSA Observed/Predicted,Abdominal SSI Observed/Predicted,Colon SSI
0,60th Medical Group (Travis AFB),Travis AFB,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,1.36425648,2.34741784,2.509760178,#VALUE!,#VALUE!,#VALUE!
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!
2,81st Medical Group (Keesler AFB),Biloxi,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,0.1,0,2.132196162,#VALUE!,#VALUE!,#VALUE!
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!

In [115]:
join6=pd.merge(join5,hgi,'outer',['Facility Name','City/Town','State'])
join6.to_csv('join6.csv',index=False)
join6.head()

,Facility Name,City/Town,State,Facilities and staff linear mean score,Communication about your procedure linear mean score,Patients' rating of the facility linear mean score,Patients recommending the facility linear mean score,County/Parish_x,Abdominopelvic accidental puncture or laceration rate,CMS Medicare PSI 90: Patient safety and adverse events composite,...,READM-30-PN-HRRP,Summary star rating,Catheter Associated Infections Observed/Predicted,Central Line Blood Infections Observed/Predicted,C.Diff Observed/Predicted,MRSA Observed/Predicted,Abdominal SSI Observed/Predicted,Colon SSI,County/Parish_y,Hospital overall rating
0,60th Medical Group (Travis AFB),Travis AFB,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,1.36425648,2.34741784,2.509760178,#VALUE!,#VALUE!,#VALUE!,SOLANO,Not Available
1,673rd Medical Group (Joint Base Elmendorf-Rich...,JBER,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!,ANCHORAGE,Not Available
2,81st Medical Group (Keesler AFB),Biloxi,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!,HARRISON,Not Available
3,88th Medical Group (Wright-Patterson AFB),Wright-Patterson AFB,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,0.1,0,2.132196162,#VALUE!,#VALUE!,#VALUE!,GREENE,Not Available
4,96th Medical Group (Eglin AFB),Eglin AFB,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,0.1,0,0,#VALUE!,#VALUE!,#VALUE!,OKALOOSA,Not Available

In [ ]:
#hvbp's